-- Migration: Add Metrics and Preferences Tables

-- 1. Member Events Table (for tracking metrics)
create table if not exists member_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  member_email text not null,
  event_type text not null, -- 'sequence_started', 'email_sent', 'sequence_completed', 'refund'
  event_data jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Add index for faster queries
create index if not exists idx_member_events_user_id on member_events(user_id);
create index if not exists idx_member_events_type on member_events(user_id, event_type);

-- Enable RLS
alter table member_events enable row level security;

-- Drop existing policies
drop policy if exists "Users can view own events" on member_events;
drop policy if exists "Users can insert own events" on member_events;

-- Create Policies
create policy "Users can view own events" on member_events
  for select using (auth.uid() = user_id);

create policy "Users can insert own events" on member_events
  for insert with check (auth.uid() = user_id);

-- 2. User Preferences Table
create table if not exists user_preferences (
  user_id uuid references auth.users primary key,
  theme text default 'light',
  email_notifications boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table user_preferences enable row level security;

-- Drop existing policies
drop policy if exists "Users can view own preferences" on user_preferences;
drop policy if exists "Users can update own preferences" on user_preferences;
drop policy if exists "Users can insert own preferences" on user_preferences;

-- Create Policies
create policy "Users can view own preferences" on user_preferences
  for select using (auth.uid() = user_id);

create policy "Users can update own preferences" on user_preferences
  for update using (auth.uid() = user_id);

create policy "Users can insert own preferences" on user_preferences
  for insert with check (auth.uid() = user_id);
