-- 1. Create a table for public profiles
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  updated_at timestamp with time zone
);

-- 2. Enable RLS on profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- 3. Sequences Table
create table if not exists sequences (
  id bigint generated by default as identity primary key,
  active boolean default false,
  content jsonb default '[]'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Add user_id column if it doesn't exist
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name = 'sequences' and column_name = 'user_id') then
    alter table sequences add column user_id uuid references auth.users;
  end if; 
end $$;

-- Enable RLS
alter table sequences enable row level security;

-- Drop existing policies to avoid conflicts
drop policy if exists "Users can view own sequences" on sequences;
drop policy if exists "Users can update own sequences" on sequences;
drop policy if exists "Users can insert own sequences" on sequences;

-- Create Policies
create policy "Users can view own sequences" on sequences
  for select using (auth.uid() = user_id);

create policy "Users can update own sequences" on sequences
  for update using (auth.uid() = user_id);

create policy "Users can insert own sequences" on sequences
  for insert with check (auth.uid() = user_id);

-- 4. Members Table
create table if not exists members (
  id bigint generated by default as identity primary key,
  email text not null,
  status text default 'Joined',
  joined_at timestamp with time zone default timezone('utc'::text, now())
);

-- Add user_id column if it doesn't exist
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name = 'members' and column_name = 'user_id') then
    alter table members add column user_id uuid references auth.users;
  end if; 
end $$;

-- Enable RLS
alter table members enable row level security;

-- Drop existing policies
drop policy if exists "Users can view own members" on members;
drop policy if exists "Users can insert own members" on members;

-- Create Policies
create policy "Users can view own members" on members
  for select using (auth.uid() = user_id);

create policy "Users can insert own members" on members
  for insert with check (auth.uid() = user_id);

-- 5. Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. Member Events Table (for tracking metrics)
create table if not exists member_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  member_email text not null,
  event_type text not null, -- 'sequence_started', 'email_sent', 'sequence_completed', 'refund'
  event_data jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Add index for faster queries
create index if not exists idx_member_events_user_id on member_events(user_id);
create index if not exists idx_member_events_type on member_events(user_id, event_type);

-- Enable RLS
alter table member_events enable row level security;

-- Drop existing policies
drop policy if exists "Users can view own events" on member_events;
drop policy if exists "Users can insert own events" on member_events;

-- Create Policies
create policy "Users can view own events" on member_events
  for select using (auth.uid() = user_id);

create policy "Users can insert own events" on member_events
  for insert with check (auth.uid() = user_id);

-- 7. User Preferences Table
create table if not exists user_preferences (
  user_id uuid references auth.users primary key,
  theme text default 'light',
  email_notifications boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table user_preferences enable row level security;

-- Drop existing policies
drop policy if exists "Users can view own preferences" on user_preferences;
drop policy if exists "Users can update own preferences" on user_preferences;
drop policy if exists "Users can insert own preferences" on user_preferences;

-- Create Policies
create policy "Users can view own preferences" on user_preferences
  for select using (auth.uid() = user_id);

create policy "Users can update own preferences" on user_preferences
  for update using (auth.uid() = user_id);

create policy "Users can insert own preferences" on user_preferences
  for insert with check (auth.uid() = user_id);
